Repository peepi-com-br/vuetify-tiptap, pull requests merged in 2022-04, with the labels that each got.

#2 Fixes disableToolbar prop
  src/components/VTiptap.vue
  src/stories/VTiptap.stories.js
Labels: fix

#1 Add dark mode
  dev/App.vue
  src/components/ColorPicker.vue
  src/components/EmojiPicker.vue
  src/components/ImageDialog.vue
  src/components/LinkDialog.vue
  src/components/VTiptap.vue
  src/components/VideoDialog.vue
Labels: enhancement, feature

#5 First tests
  .storybook/main.js
  package-lock.json
  package.json
  src/components/VTiptap.vue
  src/constants/toolbarDefinitions.ts
  src/stories/VTiptap.stories.js
Labels: feature

#7 Adds mention plugin
  package-lock.json
  package.json
  src/components/VTiptap.vue
  src/constants/suggestion.ts
  src/plugins/tiptap-kit.ts
  src/stories/VTiptap.stories.js
Labels: feature

#3 Add packs icons feature
  dev/App.vue
  dev/index.html
  dev/plugins/vuetify.ts
  src/components/EmojiPicker.vue
  src/components/VTiptap.vue
  src/constants/icons.ts
  src/constants/toolbarDefinitions.ts
Labels: feature

#9 Adds label outside the component
  .storybook/preview.js
  src/components/VTiptap.vue
  src/stories/VTiptap.stories.js
Labels: feature

#10 Refactor dialogs
  dev/App.vue
  src/components/ImageDialog.vue
  src/components/LinkDialog.vue
  src/components/VTiptap.vue
  src/components/VideoDialog.vue
  src/components/components.ts
  src/constants/toolbarDefinitions.ts
Labels: enhancement

#17 Adds prop to upload images
  README.md
  src/components/ImageDialog.vue
  src/components/UploadableImage.vue
  src/components/VTiptap.vue
  src/components/components.ts
  src/entry.esm.ts
  src/stories/VTiptap.stories.js
  src/types/options.ts
  src/utils/mapKeys.ts
  src/utils/options/index.ts
Labels: feature
